import uuid
from cassandra.cqlengine.columns import *
from cassandra.cqlengine.models import Model
from cassandra.cqlengine.usertype import UserType

class commit(UserType):
    id = UUID()
    committer_id = Integer()
    committer_name = Text(required=False)
    date = DateTime()
    message = Text(required=False)
    additions = Integer()
    deletions = Integer()
    total = Integer()


class perm_model(UserType):
    admin = Boolean()
    push = Boolean()
    pull = Boolean()


class license_model(UserType):
    key = Text(required=False)
    name = Text(required=False)
    spdx_id = Text(required=False)
    url = Text(required=False)
    node_id = Text(required=False)


class issue_model(UserType):
     body = Text(required=False)
     closed_at = Text(required=False)
     created_at = Text(required=False)
     id = Integer(required=False)
     labels =  List(value_type=Text)
     number = Integer(required=False)
     state = Text(required=False)
     title = Text(required=False)
     updated_at = Text(required=False)


class contrib_model(UserType):
     avatar_url = Text(required=False)
     contributions = Integer(required=False)
     html_url = Text(required=False)
     id = Integer(required=False)
     name = Text(required=False)

    
    
class owner_model(UserType):
    login = Text(required=False)
    id = Integer(required=False)
    node_id = Text(required=False)
    avatar_url = Text(required=False)
    gravatar_id = Text(required=False)
    url = Text(required=False)
    html_url = Text(required=False)
    followers_url = Text(required=False)
    following_url = Text(required=False)
    gists_url = Text(required=False)
    starred_url = Text(required=False)
    subscriptions_url = Text(required=False)
    organizations_url = Text(required=False)
    repos_url = Text(required=False)
    events_url = Text(required=False)
    received_events_url = Text(required=False)
    type = Text(required=False)
    site_admin = Boolean(required=False)


class Repo(Model):
    id = Integer(primary_key=True)
    node_id = Text(required=False)
    name = Text(required=False)
    full_name = Text(required=False)
    private = Boolean()
    html_url = Text(required=False)
    description = Text(required=False)
    fork = Boolean()
    url = Text(required=False)
    forks_url = Text(required=False)
    keys_url = Text(required=False)
    collaborators_url = Text(required=False)
    teams_url = Text(required=False)
    hooks_url = Text(required=False)
    issue_events_url = Text(required=False)
    events_url = Text(required=False)
    assignees_url = Text(required=False)
    branches_url = Text(required=False)
    tags_url = Text(required=False)
    blobs_url = Text(required=False)
    git_tags_url = Text(required=False)
    git_refs_url = Text(required=False)
    trees_url = Text(required=False)
    statuses_url = Text(required=False)
    languages_url = Text(required=False)
    stargazers_url = Text(required=False)
    contributors_url = Text(required=False)
    subscribers_url = Text(required=False)
    subscription_url = Text(required=False)
    commits_url = Text(required=False)
    git_commits_url = Text(required=False)
    comments_url = Text(required=False)
    issue_comment_url = Text(required=False)
    contents_url = Text(required=False)
    compare_url = Text(required=False)
    merges_url = Text(required=False)
    archive_url = Text(required=False)
    downloads_url = Text(required=False)
    issues_url = Text(required=False)
    pulls_url = Text(required=False)
    milestones_url = Text(required=False)
    notifications_url = Text(required=False)
    labels_url = Text(required=False)
    releases_url = Text(required=False)
    deployments_url = Text(required=False)
    created_at = Text(required=False)
    updated_at = Text(required=False)
    pushed_at = Text(required=False)
    git_url = Text(required=False)
    ssh_url = Text(required=False)
    clone_url = Text(required=False)
    svn_url = Text(required=False)
    homepage = Text(required=False)
    size = BigInt(required=False)
    stargazers_count = Integer(required=False)
    watchers_count = Integer(required=False)
    language = Text(required=False)
    has_issues = Boolean(required=False)
    has_projects = Boolean(required=False)
    has_downloads = Boolean(required=False)
    has_wiki = Boolean(required=False)
    has_pages = Boolean(required=False)
    forks_count =Integer(required=False)
    mirror_url = Text(required=False)
    archived = Boolean(required=False)
    disabled = Boolean(required=False)
    open_issues_count = Integer(required=False)
    license = Text(required=False)
    forks = Integer(required=False)
    open_issues = Integer(required=False)
    watchers = Integer(required=False)
    default_branch = Text(required=False)
    permissions = UserDefinedType(perm_model)
    owner = UserDefinedType(owner_model)
    languages_list = Map(key_type=Text(), value_type=Integer())
    contributors_list = List(value_type=UserDefinedType(contrib_model))
    issues_list = List(value_type=UserDefinedType(issue_model))

